platform: linux
image_resource:
  type: docker-image
  source:
    repository: publysher/hugo
    tag: latest
run:
  path: cloud-native/ci/build.sh
  dir: summit-training-classes
inputs:
- name: summit-training-classes
outputs:
- name: built
  path: built
